version: '3.4'

services:
  generic.mailsender.api:
    image: ${DOCKER_REGISTRY-}genericmailsenderapi
    build:
      context: .
      dockerfile: Generic.MailSender.Api/Dockerfile
    environment:
        Mail__Host: "fake_smtp"
        Mail__Port: 1025
        Mail__Sender: "source@test.com"
        Mail__Templates: "/var/mail-templates"
    volumes:
        - "./Generic.MailSender.Api/Templates:/var/mail-templates:ro"
  fake_smtp:
    image: mailhog/mailhog
    ports:
        - "1081:8025"
        - "1025:1025"
