version: '3.4'

services:
  generic.mailsender.api:
    image: ${DOCKER_REGISTRY-}genericmailsenderapi
    build:
      context: .
      dockerfile: Generic.MailSender.Api/Dockerfile
  fake_smtp:
    image: mailhog/mailhog
    ports:
        - "1081:8025"
        - "1025:1025"
